name: package

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libarchive-tools dpkg-dev
          
      - name: Build
        run: |
          rm -rf ./n*/
          export version=$(curl -s https://api.github.com/repos/tj/n/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          mkdir n-base
          mkdir -p n-base/DEBIAN
          mkdir -p n-base/usr/bin
          wget https://raw.githubusercontent.com/tj/n/master/bin/n -O n-base/usr/bin/n
          wget https://raw.githubusercontent.com/hmsjy2017/n-debs/master/controltemplate -O n-base/DEBIAN/control
          sed -i "s/VTR/$version/" n-base/DEBIAN/control
          chmod 755 n-base/DEBIAN/*
          dpkg-deb -b ./n-base n_"$version"_all.deb

      - name: Create symlinks
        run: |
          rm -rf ./n*/
          export version=$(curl -s https://api.github.com/repos/repos/tj/n/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          rm -rf ./*latest.deb
          ln -fs "$(find . -name '*all.deb' -type f -printf '%P\n' -quit)" n-all-latest.deb

      - name: Upload
        run: |
          rm -rf ./n*/
          export version=$(curl -s https://api.github.com/repos/tj/n/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          echo $version > current.txt
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload n v$(curl -s https://api.github.com/repos/tj/n/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')" 
          git push
